// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: service.proto

package servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceType identifies whether a managed instance is a server or client
type InstanceType int32

const (
	InstanceType_INSTANCE_TYPE_UNSPECIFIED InstanceType = 0
	InstanceType_INSTANCE_TYPE_SERVER      InstanceType = 1
	InstanceType_INSTANCE_TYPE_CLIENT      InstanceType = 2
)

// Enum value maps for InstanceType.
var (
	InstanceType_name = map[int32]string{
		0: "INSTANCE_TYPE_UNSPECIFIED",
		1: "INSTANCE_TYPE_SERVER",
		2: "INSTANCE_TYPE_CLIENT",
	}
	InstanceType_value = map[string]int32{
		"INSTANCE_TYPE_UNSPECIFIED": 0,
		"INSTANCE_TYPE_SERVER":      1,
		"INSTANCE_TYPE_CLIENT":      2,
	}
)

func (x InstanceType) Enum() *InstanceType {
	p := new(InstanceType)
	*p = x
	return p
}

func (x InstanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (InstanceType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x InstanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceType.Descriptor instead.
func (InstanceType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// InstanceInfo describes a managed instance
type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          InstanceType           `protobuf:"varint,2,opt,name=type,proto3,enum=turnable.service.v1.InstanceType" json:"type,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceInfo) GetType() InstanceType {
	if x != nil {
		return x.Type
	}
	return InstanceType_INSTANCE_TYPE_UNSPECIFIED
}

func (x *InstanceInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

// LogAttr is a single structured log attribute key/value pair
type LogAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAttr) Reset() {
	*x = LogAttr{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAttr) ProtoMessage() {}

func (x *LogAttr) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAttr.ProtoReflect.Descriptor instead.
func (*LogAttr) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *LogAttr) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogAttr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// LogRecord represents a structured log entry emitted by the service or an instance
type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attrs         []*LogAttr             `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogRecord) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *LogRecord) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetAttrs() []*LogAttr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// ServerHello is the first message sent by the service on every new connection
type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         string                 `protobuf:"bytes,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	AuthRequired  bool                   `protobuf:"varint,3,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *ServerHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerHello) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *ServerHello) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// ClientHello is sent by the client in response if auth is required
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClientHello) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *ClientHello) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// StartServerRequest starts a new Turnable server instance
type StartServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerRequest) Reset() {
	*x = StartServerRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerRequest) ProtoMessage() {}

func (x *StartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerRequest.ProtoReflect.Descriptor instead.
func (*StartServerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *StartServerRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// StartServerResponse carries the new server instance ID or an error
type StartServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerResponse) Reset() {
	*x = StartServerResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerResponse) ProtoMessage() {}

func (x *StartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerResponse.ProtoReflect.Descriptor instead.
func (*StartServerResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *StartServerResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartServerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StartClientRequest starts a new Turnable client instance
type StartClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listenAddr,proto3" json:"listenAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClientRequest) Reset() {
	*x = StartClientRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClientRequest) ProtoMessage() {}

func (x *StartClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClientRequest.ProtoReflect.Descriptor instead.
func (*StartClientRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *StartClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartClientRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

// StartClientResponse carries the new client instance ID or an error
type StartClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClientResponse) Reset() {
	*x = StartClientResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClientResponse) ProtoMessage() {}

func (x *StartClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClientResponse.ProtoReflect.Descriptor instead.
func (*StartClientResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *StartClientResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartClientResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StopInstanceRequest stops the specified managed instance
type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *StopInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// StopInstanceResponse is sent in reply to StopInstanceRequest
type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *StopInstanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateProviderRequest updates config provider data for a running server
type UpdateProviderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProviderConfig string                 `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProviderRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateProviderRequest) GetProviderConfig() string {
	if x != nil {
		return x.ProviderConfig
	}
	return ""
}

// UpdateProviderResponse is sent in reply to UpdateProviderRequest
type UpdateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderResponse) Reset() {
	*x = UpdateProviderResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderResponse) ProtoMessage() {}

func (x *UpdateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateProviderResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

// ListInstancesRequest requests the list of all managed instances
type ListInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

// ListInstancesResponse carries the list of all managed instances
type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*InstanceInfo        `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListInstancesResponse) GetInstances() []*InstanceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

// ValidateServerConfigRequest validates a server config
type ValidateServerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServerConfigRequest) Reset() {
	*x = ValidateServerConfigRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServerConfigRequest) ProtoMessage() {}

func (x *ValidateServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServerConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateServerConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ValidateServerConfigResponse reports whether the server config is valid
type ValidateServerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServerConfigResponse) Reset() {
	*x = ValidateServerConfigResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServerConfigResponse) ProtoMessage() {}

func (x *ValidateServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServerConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateServerConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateServerConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ValidateClientConfigRequest validates a client config JSON or URL
type ValidateClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientConfigRequest) Reset() {
	*x = ValidateClientConfigRequest{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientConfigRequest) ProtoMessage() {}

func (x *ValidateClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateClientConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ValidateClientConfigResponse reports whether the client config is valid
type ValidateClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientConfigResponse) Reset() {
	*x = ValidateClientConfigResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientConfigResponse) ProtoMessage() {}

func (x *ValidateClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateClientConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateClientConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ConvertClientConfigRequest converts a client config between JSON and URL form
type ConvertClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertClientConfigRequest) Reset() {
	*x = ConvertClientConfigRequest{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertClientConfigRequest) ProtoMessage() {}

func (x *ConvertClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertClientConfigRequest.ProtoReflect.Descriptor instead.
func (*ConvertClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ConvertClientConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ConvertClientConfigResponse returns the converted client config
type ConvertClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertClientConfigResponse) Reset() {
	*x = ConvertClientConfigResponse{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertClientConfigResponse) ProtoMessage() {}

func (x *ConvertClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertClientConfigResponse.ProtoReflect.Descriptor instead.
func (*ConvertClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ConvertClientConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ErrorResponse returns a fatal protocol-level error
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request is a client-to-service message
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_StartServer
	//	*Request_StartClient
	//	*Request_StopInstance
	//	*Request_UpdateProvider
	//	*Request_ListInstances
	//	*Request_ValidateServerConfig
	//	*Request_ValidateClientConfig
	//	*Request_ConvertClientConfig
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetStartServer() *StartServerRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_StartServer); ok {
			return x.StartServer
		}
	}
	return nil
}

func (x *Request) GetStartClient() *StartClientRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_StartClient); ok {
			return x.StartClient
		}
	}
	return nil
}

func (x *Request) GetStopInstance() *StopInstanceRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_StopInstance); ok {
			return x.StopInstance
		}
	}
	return nil
}

func (x *Request) GetUpdateProvider() *UpdateProviderRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_UpdateProvider); ok {
			return x.UpdateProvider
		}
	}
	return nil
}

func (x *Request) GetListInstances() *ListInstancesRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_ListInstances); ok {
			return x.ListInstances
		}
	}
	return nil
}

func (x *Request) GetValidateServerConfig() *ValidateServerConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_ValidateServerConfig); ok {
			return x.ValidateServerConfig
		}
	}
	return nil
}

func (x *Request) GetValidateClientConfig() *ValidateClientConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_ValidateClientConfig); ok {
			return x.ValidateClientConfig
		}
	}
	return nil
}

func (x *Request) GetConvertClientConfig() *ConvertClientConfigRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_ConvertClientConfig); ok {
			return x.ConvertClientConfig
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_StartServer struct {
	StartServer *StartServerRequest `protobuf:"bytes,1,opt,name=start_server,json=startServer,proto3,oneof"`
}

type Request_StartClient struct {
	StartClient *StartClientRequest `protobuf:"bytes,2,opt,name=start_client,json=startClient,proto3,oneof"`
}

type Request_StopInstance struct {
	StopInstance *StopInstanceRequest `protobuf:"bytes,3,opt,name=stop_instance,json=stopInstance,proto3,oneof"`
}

type Request_UpdateProvider struct {
	UpdateProvider *UpdateProviderRequest `protobuf:"bytes,4,opt,name=update_provider,json=updateProvider,proto3,oneof"`
}

type Request_ListInstances struct {
	ListInstances *ListInstancesRequest `protobuf:"bytes,5,opt,name=list_instances,json=listInstances,proto3,oneof"`
}

type Request_ValidateServerConfig struct {
	ValidateServerConfig *ValidateServerConfigRequest `protobuf:"bytes,6,opt,name=validate_server_config,json=validateServerConfig,proto3,oneof"`
}

type Request_ValidateClientConfig struct {
	ValidateClientConfig *ValidateClientConfigRequest `protobuf:"bytes,7,opt,name=validate_client_config,json=validateClientConfig,proto3,oneof"`
}

type Request_ConvertClientConfig struct {
	ConvertClientConfig *ConvertClientConfigRequest `protobuf:"bytes,8,opt,name=convert_client_config,json=convertClientConfig,proto3,oneof"`
}

func (*Request_StartServer) isRequest_Payload() {}

func (*Request_StartClient) isRequest_Payload() {}

func (*Request_StopInstance) isRequest_Payload() {}

func (*Request_UpdateProvider) isRequest_Payload() {}

func (*Request_ListInstances) isRequest_Payload() {}

func (*Request_ValidateServerConfig) isRequest_Payload() {}

func (*Request_ValidateClientConfig) isRequest_Payload() {}

func (*Request_ConvertClientConfig) isRequest_Payload() {}

// Response is a service-to-client message
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_StartServer
	//	*Response_StartClient
	//	*Response_StopInstance
	//	*Response_UpdateProvider
	//	*Response_ListInstances
	//	*Response_LogRecord
	//	*Response_Error
	//	*Response_ValidateServerConfig
	//	*Response_ValidateClientConfig
	//	*Response_ConvertClientConfig
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetStartServer() *StartServerResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_StartServer); ok {
			return x.StartServer
		}
	}
	return nil
}

func (x *Response) GetStartClient() *StartClientResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_StartClient); ok {
			return x.StartClient
		}
	}
	return nil
}

func (x *Response) GetStopInstance() *StopInstanceResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_StopInstance); ok {
			return x.StopInstance
		}
	}
	return nil
}

func (x *Response) GetUpdateProvider() *UpdateProviderResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_UpdateProvider); ok {
			return x.UpdateProvider
		}
	}
	return nil
}

func (x *Response) GetListInstances() *ListInstancesResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ListInstances); ok {
			return x.ListInstances
		}
	}
	return nil
}

func (x *Response) GetLogRecord() *LogRecord {
	if x != nil {
		if x, ok := x.Payload.(*Response_LogRecord); ok {
			return x.LogRecord
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetValidateServerConfig() *ValidateServerConfigResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ValidateServerConfig); ok {
			return x.ValidateServerConfig
		}
	}
	return nil
}

func (x *Response) GetValidateClientConfig() *ValidateClientConfigResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ValidateClientConfig); ok {
			return x.ValidateClientConfig
		}
	}
	return nil
}

func (x *Response) GetConvertClientConfig() *ConvertClientConfigResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ConvertClientConfig); ok {
			return x.ConvertClientConfig
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_StartServer struct {
	StartServer *StartServerResponse `protobuf:"bytes,1,opt,name=start_server,json=startServer,proto3,oneof"`
}

type Response_StartClient struct {
	StartClient *StartClientResponse `protobuf:"bytes,2,opt,name=start_client,json=startClient,proto3,oneof"`
}

type Response_StopInstance struct {
	StopInstance *StopInstanceResponse `protobuf:"bytes,3,opt,name=stop_instance,json=stopInstance,proto3,oneof"`
}

type Response_UpdateProvider struct {
	UpdateProvider *UpdateProviderResponse `protobuf:"bytes,4,opt,name=update_provider,json=updateProvider,proto3,oneof"`
}

type Response_ListInstances struct {
	ListInstances *ListInstancesResponse `protobuf:"bytes,5,opt,name=list_instances,json=listInstances,proto3,oneof"`
}

type Response_LogRecord struct {
	LogRecord *LogRecord `protobuf:"bytes,6,opt,name=log_record,json=logRecord,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type Response_ValidateServerConfig struct {
	ValidateServerConfig *ValidateServerConfigResponse `protobuf:"bytes,8,opt,name=validate_server_config,json=validateServerConfig,proto3,oneof"`
}

type Response_ValidateClientConfig struct {
	ValidateClientConfig *ValidateClientConfigResponse `protobuf:"bytes,9,opt,name=validate_client_config,json=validateClientConfig,proto3,oneof"`
}

type Response_ConvertClientConfig struct {
	ConvertClientConfig *ConvertClientConfigResponse `protobuf:"bytes,10,opt,name=convert_client_config,json=convertClientConfig,proto3,oneof"`
}

func (*Response_StartServer) isResponse_Payload() {}

func (*Response_StartClient) isResponse_Payload() {}

func (*Response_StopInstance) isResponse_Payload() {}

func (*Response_UpdateProvider) isResponse_Payload() {}

func (*Response_ListInstances) isResponse_Payload() {}

func (*Response_LogRecord) isResponse_Payload() {}

func (*Response_Error) isResponse_Payload() {}

func (*Response_ValidateServerConfig) isResponse_Payload() {}

func (*Response_ValidateClientConfig) isResponse_Payload() {}

func (*Response_ConvertClientConfig) isResponse_Payload() {}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x13turnable.service.v1\"o\n" +
	"\fInstanceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.turnable.service.v1.InstanceTypeR\x04type\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\"1\n" +
	"\aLogAttr\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x83\x01\n" +
	"\tLogRecord\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x122\n" +
	"\x05attrs\x18\x04 \x03(\v2\x1c.turnable.service.v1.LogAttrR\x05attrs\"\x81\x01\n" +
	"\vServerHello\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\tR\x05magic\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12#\n" +
	"\rauth_required\x18\x03 \x01(\bR\fauthRequired\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"L\n" +
	"\vClientHello\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\",\n" +
	"\x12StartServerRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"L\n" +
	"\x13StartServerResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x12StartClientRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x1e\n" +
	"\n" +
	"listenAddr\x18\x02 \x01(\tR\n" +
	"listenAddr\"L\n" +
	"\x13StartClientResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x13StopInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\",\n" +
	"\x14StopInstanceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"a\n" +
	"\x15UpdateProviderRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0fprovider_config\x18\x02 \x01(\tR\x0eproviderConfig\"\x18\n" +
	"\x16UpdateProviderResponse\"\x16\n" +
	"\x14ListInstancesRequest\"X\n" +
	"\x15ListInstancesResponse\x12?\n" +
	"\tinstances\x18\x01 \x03(\v2!.turnable.service.v1.InstanceInfoR\tinstances\"5\n" +
	"\x1bValidateServerConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"J\n" +
	"\x1cValidateServerConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x1bValidateClientConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"J\n" +
	"\x1cValidateClientConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x1aConvertClientConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"5\n" +
	"\x1bConvertClientConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe7\x05\n" +
	"\aRequest\x12L\n" +
	"\fstart_server\x18\x01 \x01(\v2'.turnable.service.v1.StartServerRequestH\x00R\vstartServer\x12L\n" +
	"\fstart_client\x18\x02 \x01(\v2'.turnable.service.v1.StartClientRequestH\x00R\vstartClient\x12O\n" +
	"\rstop_instance\x18\x03 \x01(\v2(.turnable.service.v1.StopInstanceRequestH\x00R\fstopInstance\x12U\n" +
	"\x0fupdate_provider\x18\x04 \x01(\v2*.turnable.service.v1.UpdateProviderRequestH\x00R\x0eupdateProvider\x12R\n" +
	"\x0elist_instances\x18\x05 \x01(\v2).turnable.service.v1.ListInstancesRequestH\x00R\rlistInstances\x12h\n" +
	"\x16validate_server_config\x18\x06 \x01(\v20.turnable.service.v1.ValidateServerConfigRequestH\x00R\x14validateServerConfig\x12h\n" +
	"\x16validate_client_config\x18\a \x01(\v20.turnable.service.v1.ValidateClientConfigRequestH\x00R\x14validateClientConfig\x12e\n" +
	"\x15convert_client_config\x18\b \x01(\v2/.turnable.service.v1.ConvertClientConfigRequestH\x00R\x13convertClientConfigB\t\n" +
	"\apayload\"\xed\x06\n" +
	"\bResponse\x12M\n" +
	"\fstart_server\x18\x01 \x01(\v2(.turnable.service.v1.StartServerResponseH\x00R\vstartServer\x12M\n" +
	"\fstart_client\x18\x02 \x01(\v2(.turnable.service.v1.StartClientResponseH\x00R\vstartClient\x12P\n" +
	"\rstop_instance\x18\x03 \x01(\v2).turnable.service.v1.StopInstanceResponseH\x00R\fstopInstance\x12V\n" +
	"\x0fupdate_provider\x18\x04 \x01(\v2+.turnable.service.v1.UpdateProviderResponseH\x00R\x0eupdateProvider\x12S\n" +
	"\x0elist_instances\x18\x05 \x01(\v2*.turnable.service.v1.ListInstancesResponseH\x00R\rlistInstances\x12?\n" +
	"\n" +
	"log_record\x18\x06 \x01(\v2\x1e.turnable.service.v1.LogRecordH\x00R\tlogRecord\x12:\n" +
	"\x05error\x18\a \x01(\v2\".turnable.service.v1.ErrorResponseH\x00R\x05error\x12i\n" +
	"\x16validate_server_config\x18\b \x01(\v21.turnable.service.v1.ValidateServerConfigResponseH\x00R\x14validateServerConfig\x12i\n" +
	"\x16validate_client_config\x18\t \x01(\v21.turnable.service.v1.ValidateClientConfigResponseH\x00R\x14validateClientConfig\x12f\n" +
	"\x15convert_client_config\x18\n" +
	" \x01(\v20.turnable.service.v1.ConvertClientConfigResponseH\x00R\x13convertClientConfigB\t\n" +
	"\apayload*a\n" +
	"\fInstanceType\x12\x1d\n" +
	"\x19INSTANCE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INSTANCE_TYPE_SERVER\x10\x01\x12\x18\n" +
	"\x14INSTANCE_TYPE_CLIENT\x10\x02B<Z:github.com/theairblow/turnable/pkg/service/proto;servicepbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_service_proto_goTypes = []any{
	(InstanceType)(0),                    // 0: turnable.service.v1.InstanceType
	(*InstanceInfo)(nil),                 // 1: turnable.service.v1.InstanceInfo
	(*LogAttr)(nil),                      // 2: turnable.service.v1.LogAttr
	(*LogRecord)(nil),                    // 3: turnable.service.v1.LogRecord
	(*ServerHello)(nil),                  // 4: turnable.service.v1.ServerHello
	(*ClientHello)(nil),                  // 5: turnable.service.v1.ClientHello
	(*StartServerRequest)(nil),           // 6: turnable.service.v1.StartServerRequest
	(*StartServerResponse)(nil),          // 7: turnable.service.v1.StartServerResponse
	(*StartClientRequest)(nil),           // 8: turnable.service.v1.StartClientRequest
	(*StartClientResponse)(nil),          // 9: turnable.service.v1.StartClientResponse
	(*StopInstanceRequest)(nil),          // 10: turnable.service.v1.StopInstanceRequest
	(*StopInstanceResponse)(nil),         // 11: turnable.service.v1.StopInstanceResponse
	(*UpdateProviderRequest)(nil),        // 12: turnable.service.v1.UpdateProviderRequest
	(*UpdateProviderResponse)(nil),       // 13: turnable.service.v1.UpdateProviderResponse
	(*ListInstancesRequest)(nil),         // 14: turnable.service.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),        // 15: turnable.service.v1.ListInstancesResponse
	(*ValidateServerConfigRequest)(nil),  // 16: turnable.service.v1.ValidateServerConfigRequest
	(*ValidateServerConfigResponse)(nil), // 17: turnable.service.v1.ValidateServerConfigResponse
	(*ValidateClientConfigRequest)(nil),  // 18: turnable.service.v1.ValidateClientConfigRequest
	(*ValidateClientConfigResponse)(nil), // 19: turnable.service.v1.ValidateClientConfigResponse
	(*ConvertClientConfigRequest)(nil),   // 20: turnable.service.v1.ConvertClientConfigRequest
	(*ConvertClientConfigResponse)(nil),  // 21: turnable.service.v1.ConvertClientConfigResponse
	(*ErrorResponse)(nil),                // 22: turnable.service.v1.ErrorResponse
	(*Request)(nil),                      // 23: turnable.service.v1.Request
	(*Response)(nil),                     // 24: turnable.service.v1.Response
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: turnable.service.v1.InstanceInfo.type:type_name -> turnable.service.v1.InstanceType
	2,  // 1: turnable.service.v1.LogRecord.attrs:type_name -> turnable.service.v1.LogAttr
	1,  // 2: turnable.service.v1.ListInstancesResponse.instances:type_name -> turnable.service.v1.InstanceInfo
	6,  // 3: turnable.service.v1.Request.start_server:type_name -> turnable.service.v1.StartServerRequest
	8,  // 4: turnable.service.v1.Request.start_client:type_name -> turnable.service.v1.StartClientRequest
	10, // 5: turnable.service.v1.Request.stop_instance:type_name -> turnable.service.v1.StopInstanceRequest
	12, // 6: turnable.service.v1.Request.update_provider:type_name -> turnable.service.v1.UpdateProviderRequest
	14, // 7: turnable.service.v1.Request.list_instances:type_name -> turnable.service.v1.ListInstancesRequest
	16, // 8: turnable.service.v1.Request.validate_server_config:type_name -> turnable.service.v1.ValidateServerConfigRequest
	18, // 9: turnable.service.v1.Request.validate_client_config:type_name -> turnable.service.v1.ValidateClientConfigRequest
	20, // 10: turnable.service.v1.Request.convert_client_config:type_name -> turnable.service.v1.ConvertClientConfigRequest
	7,  // 11: turnable.service.v1.Response.start_server:type_name -> turnable.service.v1.StartServerResponse
	9,  // 12: turnable.service.v1.Response.start_client:type_name -> turnable.service.v1.StartClientResponse
	11, // 13: turnable.service.v1.Response.stop_instance:type_name -> turnable.service.v1.StopInstanceResponse
	13, // 14: turnable.service.v1.Response.update_provider:type_name -> turnable.service.v1.UpdateProviderResponse
	15, // 15: turnable.service.v1.Response.list_instances:type_name -> turnable.service.v1.ListInstancesResponse
	3,  // 16: turnable.service.v1.Response.log_record:type_name -> turnable.service.v1.LogRecord
	22, // 17: turnable.service.v1.Response.error:type_name -> turnable.service.v1.ErrorResponse
	17, // 18: turnable.service.v1.Response.validate_server_config:type_name -> turnable.service.v1.ValidateServerConfigResponse
	19, // 19: turnable.service.v1.Response.validate_client_config:type_name -> turnable.service.v1.ValidateClientConfigResponse
	21, // 20: turnable.service.v1.Response.convert_client_config:type_name -> turnable.service.v1.ConvertClientConfigResponse
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[22].OneofWrappers = []any{
		(*Request_StartServer)(nil),
		(*Request_StartClient)(nil),
		(*Request_StopInstance)(nil),
		(*Request_UpdateProvider)(nil),
		(*Request_ListInstances)(nil),
		(*Request_ValidateServerConfig)(nil),
		(*Request_ValidateClientConfig)(nil),
		(*Request_ConvertClientConfig)(nil),
	}
	file_service_proto_msgTypes[23].OneofWrappers = []any{
		(*Response_StartServer)(nil),
		(*Response_StartClient)(nil),
		(*Response_StopInstance)(nil),
		(*Response_UpdateProvider)(nil),
		(*Response_ListInstances)(nil),
		(*Response_LogRecord)(nil),
		(*Response_Error)(nil),
		(*Response_ValidateServerConfig)(nil),
		(*Response_ValidateClientConfig)(nil),
		(*Response_ConvertClientConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
